---
name: tinc

releases:
- name: tinc-vpn
  version: latest

update:
  canaries: 1
  canary_watch_time: 15000-30000
  update_watch_time: 15000-30000
  max_in_flight: 2

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: tinc
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default

  jobs:
  - name: tinc
    release: tinc-vpn
  properties:
    tinc:
      name: test
      ip: 10.96.15.5
      netmask: 255.255.255.0
      cidr: 10.96.15.0/24
      private_key: ((key.private_key))
      public_key: ((key.public_key))

variables:
- name: key
  type: rsa
